version: '3.8'

services:
  benchmark:
    build: .
    image: ghcr.io/donjulve/compiler-benchmark:latest
    volumes:
      - ./Informes:/app/Informes
      - ./Gráficas:/app/Gráficas
      - ./programs:/app/programs
      - ./scripts:/app/scripts
      - ./results_g++:/app/results_g++
      - ./results_clang++:/app/results_clang++
      - ./results_rustc:/app/results_rustc
    working_dir: /app

