version: '3.8'

services:
  benchmark:
    build: .
    image: ghcr.io/donjulve/compiler-benchmark:latest
    volumes:
      - ./Informes:/app/Informes
      - ./Gráficas:/app/Gráficas
      - ./programs:/app/programs
      - ./scripts:/app/scripts
      - ./results_g++:/app/results_g++
      - ./results_clang:/app/results_clang
      - ./results_rust:/app/results_rust
    working_dir: /app

volumes:
  informes:
  graficas:
  programs:
  scripts:
  results_g++:
  results_clang:
  results_rust:
